[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[project]
name = "vs-tensorrt-builder-cu129-base"
version = "16.2.3"
requires-python = ">=3.12"
description = "TensorRT 11.1 PTX and SM75-SM89 builder resources for vs-mlrt"
dependencies = ["vs-tensorrt-core-cu129==16.2.3"]

[tool.hatch.build.targets.wheel]
bypass-selection = true

[tool.hatch.build.hooks.custom]
path = "../component_hook.py"
