schema_version = 1
management = "subtree"
distribution = "csmod"
wheel_version = "0.3.0.post1+alice.1"
import_name = "CSMOD"
runtime_kind = "module"
upstream_url = "https://github.com/fdar0536/VapourSynth-Contra-Sharpen-mod"
upstream_revision = "b9ff7253bf217dded071b88fb8a6d212aceb81f4"
upstream_import_commit = "03e969984742a71409376c4de6898b6a5975355f"
vendored_url = "https://github.com/fdar0536/VapourSynth-Contra-Sharpen-mod/blob/master/CSMOD.py"
vendored_revision = "b9ff7253bf217dded071b88fb8a6d212aceb81f4"
intermediate_commits = []
collection_repository = "https://github.com/RyougiKukoc/VapourSynth-Scripts-Collection"
collection_revision = "14091484381778fe55102b58ac584e38f5e0fc6a"
collection_runtime_source = "scripts/CSMOD/CSMOD.py"
collection_commits = ["99759cf98ea1feb3c7a4830ab18644e07e750e91", "962b01c4c6928cb01a57621531c0a96d61338f51", "67a7bac3d365dcca5200054cb1fe37cdfab7d295"]
license_observation = "Not separately declared"

[runtime_sha256]
"CSMOD.py" = "33816f846fb74d0db2bdfdb888834ef097a9dc0d1d2245dbacc1673c529d3d29"
