"""Validate a pure Python wheel against a separately resolved source plan."""
from __future__ import annotations

import argparse
import base64
import csv
import fnmatch
import hashlib
import io
import json
import platform
import stat
import sys
import zipfile
from email.parser import BytesParser
from pathlib import Path, PurePosixPath

from packaging.requirements import Requirement
from packaging.specifiers import SpecifierSet
from packaging.utils import canonicalize_name, parse_wheel_filename
from packaging.version import Version

from module_common import check_plan, digest_file, load_registry, read_json, relative_path, require, write_json


def validate_wheel(wheel: Path, plan: dict) -> dict:
    name, version, build, tags = parse_wheel_filename(wheel.name)
    require(name == plan["distribution"] and version == Version(plan["version"]), "wheel filename name/version disagrees with source")
    allowed_tags = {"py3-none-any", "py2-none-any"}
    wheel_tags = {str(tag) for tag in tags}
    require(not build and "py3-none-any" in wheel_tags and wheel_tags <= allowed_tags, "API v1 accepts pure Python wheels with Python 3, no ABI/platform requirement and no build tags")
    with zipfile.ZipFile(wheel) as archive:
        entries = archive.infolist()
        names = [entry.filename for entry in entries]
        require(len(names) == len(set(names)), "duplicate wheel paths")
        require(sum(entry.file_size for entry in entries) <= 100 * 1024 * 1024, "wheel exceeds unpacked size limit")
        files = {}
        distinfos = set()
        for entry in entries:
            path = entry.filename.rstrip("/")
            relative_path(path)
            require(not stat.S_ISLNK(entry.external_attr >> 16), "wheel must not contain symlinks")
            top = PurePosixPath(path).parts[0]
            require(top == plan["import_name"] or top.endswith(".dist-info"), "wheel writes outside its package and metadata")
            require(PurePosixPath(path).suffix.lower() not in {".dll", ".so", ".pyd", ".exe", ".pyc"}, "native or generated bytecode file in pure Python module wheel")
            if top.endswith(".dist-info"):
                distinfos.add(top)
            if not entry.is_dir():
                files[path] = archive.read(entry)
        require(len(distinfos) == 1, "expected exactly one dist-info directory")
        distinfo = distinfos.pop()
        expected_distinfo = f"{wheel.name.split('-')[0]}-{plan['version']}.dist-info"
        require(distinfo == expected_distinfo, "dist-info directory disagrees with wheel filename")
        require(f"{plan['import_name']}/__init__.py" in files, "missing import package")
        for pattern in plan["required_files"]:
            require(any(fnmatch.fnmatchcase(name, pattern) for name in files), f"missing required wheel file: {pattern}")
        metadata_path, wheel_path, record_path = (f"{distinfo}/{name}" for name in ("METADATA", "WHEEL", "RECORD"))
        require(all(name in files for name in (metadata_path, wheel_path, record_path)), "missing wheel metadata")
        metadata = BytesParser().parsebytes(files[metadata_path])
        require(len(metadata.get_all("Name", [])) == len(metadata.get_all("Version", [])) == 1, "missing or duplicate project metadata")
        require(canonicalize_name(metadata["Name"]) == plan["distribution"] and Version(metadata["Version"]) == Version(plan["version"]), "METADATA name/version disagrees with source")
        dependencies = sorted(str(Requirement(item)) for item in metadata.get_all("Requires-Dist", []))
        require(dependencies == plan["dependencies"], "wheel changed upstream dependencies")
        requires_python = metadata.get("Requires-Python", "")
        require(SpecifierSet(requires_python) == SpecifierSet(plan["requires_python"]), "wheel changed upstream Requires-Python")
        headers = BytesParser().parsebytes(files[wheel_path])
        require(headers.get("Root-Is-Purelib", "").lower() == "true" and set(headers.get_all("Tag", [])) == wheel_tags, "WHEEL tags disagree with filename or pure Python policy")
        for name, content in files.items():
            if name.endswith(".py"):
                compile(content, name, "exec")
        records = list(csv.reader(io.StringIO(files[record_path].decode("utf-8"))))
        require(all(len(row) == 3 for row in records), "invalid RECORD")
        require(len(records) == len(files) and len({row[0] for row in records}) == len(records), "RECORD does not uniquely list every wheel file")
        for name, encoded, size in records:
            require(name in files, "RECORD names a missing file")
            if name == record_path:
                require(not encoded and not size, "RECORD must not hash itself")
            else:
                expected = base64.urlsafe_b64encode(hashlib.sha256(files[name]).digest()).decode().rstrip("=")
                require(encoded == f"sha256={expected}" and size == str(len(files[name])), f"RECORD digest/size mismatch: {name}")
        return {
            **plan, "wheel": wheel.name, "sha256": digest_file(wheel),
            "size": wheel.stat().st_size, "generator": headers.get("Generator", ""),
            "files": sorted(files),
            "file_sha256": {name: hashlib.sha256(content).hexdigest() for name, content in files.items() if name != record_path},
            "requires_dist": metadata.get_all("Requires-Dist", []),
            "validation": {
                "metadata": "passed", "record": "passed", "required_files": "passed",
                "python_syntax": "passed", "runtime_import": "not tested: runtime dependencies are user-managed",
                "python": platform.python_version(), "platform": sys.platform,
            },
        }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--plan", type=Path, required=True)
    parser.add_argument("--wheel-dir", type=Path, required=True)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    try:
        plan = read_json(args.plan)
        check_plan(plan, load_registry())
        wheels = list(args.wheel_dir.glob("*.whl"))
        require(len(wheels) == 1, "expected exactly one wheel")
        manifest = validate_wheel(wheels[0], plan)
        if args.output:
            write_json(args.output, manifest)
        print(json.dumps({"module": plan["module"], "wheel": manifest["wheel"], "sha256": manifest["sha256"], "validation": manifest["validation"]}, indent=2))
    except (ValueError, KeyError, zipfile.BadZipFile) as error:
        parser.exit(1, f"{error}\n")


if __name__ == "__main__":
    main()
