[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[project]
name = "vs-mlrt-cu129"
version = "16.2.6"
description = "VapourSynth ML runtime tools with CUDA 12.9 backends"
requires-python = ">=3.12"
license = "GPL-3.0-or-later"
dependencies = [
  "vapoursynth>=75",
  "numpy",
  "onnx",
  "onnxconverter-common",
  "vs-mlrt-models==16.2.2",
  "vs-ov==16.2.2",
  "vs-ncnn==16.2.2",
  "vs-tensorrt-core-cu129==16.2.2",
  "vs-tensorrt-builder-cu129-base==16.2.2",
  "vs-tensorrt-builder-cu129-modern==16.2.2",
  "vs-trtexec-cu129==16.2.2",
  "vs-trt-cu129==16.2.2",
  "vs-tensorrt-rtx-cu129==16.2.2",
  "vs-trt-rtx-cu129==16.2.2",
]

[project.urls]
"Source Code" = "https://github.com/AliceTeaParty/vapoursynth-api4-wheels/tree/main/plugins/vs-mlrt"
"Releases" = "https://github.com/AliceTeaParty/vapoursynth-api4-wheels/releases/tag/vs-mlrt-v16.2.6"

[tool.hatch.build.targets.wheel]
bypass-selection = true

[tool.hatch.build.hooks.custom]
path = "hatch_build.py"
