schema_version = 1
repository = "RyougiKukoc/rkstool"
repository_id = 661508831
distribution = "rkstool"
import_name = "rkstool"
project_subdirectory = "."
default_ref = "main"
requesters = ["RyougiKukoc"]
required_files = ["rkstool/__init__.py"]
